### ISSUE TITLE
Is it supporting thunk?

### ISSUE THREAD

**Issue by raitucarp** [keajs/kea#10]
Hi, I love how kea abstract things. But is it supporting redux-thunk or not? Do you have sort of road map for supporting X in the future?

**Comment by mariusandra** [comment]
Hey, I'm not sure I fully understand the question.

In theory you can use `kea` with `redux-thunk` without problems. You may access all the regular action creators from created `kea({})` logic stores [like so](https://github.com/keajs/kea#redux-all-the-way). Then you can use them in your thunks.

You can also most likely dispatch actions that are *thunked* normally, although I haven't tested that.

However, I do recommend if you want to use `kea`, to move away from `redux-thunk` and instead use `redux-saga` to manage your side effects. The simplest example for a saga action is this:

```js
const exampleLogic = kea({
  actions: () => ({
    start: true,
    resultsFetched: (results) => ({ results })
  }),

  takeEvery: ({ actions, workers }) => ({
    [actions.start]: function * () {
      const { resultsFetched } = this.actions

      const results = yield api.DoSomething()
      yield put(resultsFetched(results))

      // ... etc
    }
  })
})
```

Then either connect this to your component with `@exampleLogic` or `@connect` and run `this.actions.start()` anywhere in your component to run the saga.

Hope this helps :)

**Comment by raitucarp** [comment]
Hi, thanks for your response.

So, if I use thunk, I can use dispatch like this :

```js
actions() => ({
   increment: async (dispatch) => {
       const amount = await apiFetch();
       dispatch({ amount });
   }
})
```
right? Correct me if I'm wrong.

**Comment by mariusandra** [comment]
Hey, assuming your code example was meant to be written indised `kea({ ... })` calls, no, that won't work. In kea all actions are simple pure functions that have no side effects. You then use `takeEvery`/`takeLatest` to watch for the actions being triggered and act accordingly.

This is a design decision so that your interactions would only have one starting point: actions. Sagas and reducers can listen to them and act accordingly.

While `redux-thunk` is great for small applications, for some of which `kea` might be considered overkill, from my experience, as your app grows, it will outgrow what redux-thunk offers. 

That plus the comments in #14 describe why kea is a better approach for most larger apps, at least from my perspective.

**Comment by raitucarp** [comment]
Ah.. I see.. I should look saga more seriously, then. Thank you for your confirmation.
