### ISSUE TITLE
selectors in connected logic with keys throws an exception

### ISSUE THREAD

**Issue by AnsonT** [keajs/kea#122]
```javascript
import { kea, MakeLogicType } from 'kea'

interface AValues {
  value: string
}

interface AActions {
  loadValue: () => string
}

interface AProps {
  id: string
}

type ALogicType = MakeLogicType<AValues, AActions, AProps>

export const aLogic = kea<ALogicType>({
 path: (key: string) => ['scenes', 'aLogic', key || 'index' ],
  // key: (props) => props.id,
  defaults: {
    value: 'defaultValue',
  },
  reducers: () => ({
  }),
  loaders: ({ values, props }) => ({
    value: {
      loadValue: () => {
        return `Loaded Value ${props.id}`
      }
    }
  }),
  events: ({ actions, props }) => ({
    afterMount: [actions.loadValue]
  })
})

interface BValues {
  valueFromA: string
}

interface BActions {
}

interface BProps {
  id: string
}

type BLogicType = MakeLogicType<BValues, BActions, BProps>

export const bLogic = kea<BLogicType>({
  path: (key: string) => ['scenes', 'bLogic', key],
  key: (props) => props.id,
  connect: [aLogic],
  defaults: {
    valueFromA: 'unknown'
  },
  actions: () => ({
  }),
  reducers: () => ({
  }),
  selectors: {
    valueFromA: [
      () => [aLogic.selectors.value],
      (value: string) => `Selected from A ${value}`
    ]
  },
})

<snip>
const { valueFromA: a } = useValues(bLogic({ id: 'a' }))
const { valueFromA: b } = useValues(bLogic({ id: 'b' }))
```

bLogic connects to aLogic where Props is used to parameterize aLogic (e.g. to load a specific set of data). The selector bLogic.selectors.valueFromA will thrown an exception is there's a key assigned to aLogic.

To reproduce, comment out the path, and key properties in these logics. Without the key on aLogic. values a & b above will be the same because of caching.

Also unexpected is that the Props are automatically passed to the connected logic. I would expect that I can pass a different set of props to the connected logic.

**Comment by AnsonT** [comment]
@mariusandra I see that you blogged about this use case for the upcoming 2.3. However, I'm not sure this issue with connected logic with keys can be fixed from the React side with ReactContext.

**Comment by mariusandra** [comment]
Hey, you have a very interesting use case! I can share a few bits of context here to help explain the behaviour.

> The selector `bLogic.selectors.valueFromA` will thrown an exception is there's a key assigned to aLogic.

When there's a key assigned to a logic, you need to build the logic in order to access its values. This is done by running `aLogic(props)`. That's why this won't work:

```js
    valueFromA: [
      () => [aLogic.selectors.value],
      (value: string) => `Selected from A ${value}`
    ]
```

but this will:

```js
    selectors: ({ props }) => ({
      valueFromA: [
        () => [aLogic(props).selectors.value], 
        (value) => `Selected from A ${value}`
      ],
    }),
```

> Without the key on aLogic. values a & b above will be the same because of caching.

Actually it's technically not caching, but without the key, there there will always be at most one instance of `aLogic` running. It's mounted when you run `useValues(bLogic({ id: 'a' }))` the first time... and thus the `afterMount` will fire only once, when the props had `"a"` as the `id`.

> Also unexpected is that the Props are automatically passed to the connected logic. I would expect that I can pass a different set of props to the connected logic.

Hmm, that's indeed a convenience feature since you would often have all logics keyed on the same prop. To change what's passed use this:

```js
  connect: (props) => [aLogic(props)],
  // e.g. pass only the `id` prop:
  connect: ({ id }) => [aLogic({ id })],
```

Hope this helps :).

> I see that you blogged about this use case for the upcoming 2.3. However, I'm not sure this issue with connected logic with keys can be fixed from the React side with ReactContext.

Indeed, that won't make a difference here. Even if you use `<BindLogic logic={aLogic} props={...}>` and also `<BindLogic logic={bLogic} props={...}>`, then this only affects the `useValue(aLogic)` calls. Inside `bLogic`, when you want to access values from `aLogic`, you still need to pass the props between them correctly.

**Comment by AnsonT** [comment]
Thank you that works for my scenario.

Adding this to the documentation would be great
