### ISSUE TITLE
Integration with ReactQL

### ISSUE THREAD

**Issue by wmhafiz** [keajs/kea#20]
Currently I'm using [ReactQL](https://reactql.org/) for my go-to starter as it offers a seemless development environment for React/Redux/Apollo/Webpack stack

from their [documentation](https://reactql.org/docs/):

> ReactQL is React + GraphQL done properly — for Mac, Windows and Linux.
>
> It combines best-of-breed choices for UI, GraphQL data fetching, CSS and code bundling, > handles server-side rendering (SSR) properly, and is fast and extensible. You can choose Javascript or Typescript flavours.
>
> It focuses on performance characteristics that you don't often find in other starter kits — offering Zopfli/Brotli compression, automatic vendor splitting, aggressive minification of JS/CSS, instant hot code reloading and more, out-the-box.
>
> It pairs an async web server for handling SSR, non-JS imports (like images, CSS, etc) and works universally. Your code will run both in the browser, and on the server — even inline imports!
>
> Development, production and even static bundling can be invoked with just one command, via the ReactQL CLI.
>
> You can easily bolt-on your own GraphQL server, or point to one off-site.
>
> If you want to shave weeks off your next project boilerplate, try ReactQL.

If you could help me to get it working, i'll try to submit a PR on [reactql kit repository](https://github.com/reactql/kit) and convince the ReactQL author to get it officially supported. 

The kea starter kit is good, but I believe if we could get more boilerplate to use Kea, it will bring more attention to the community and more people will start using the library.

This is what I have so far:
https://github.com/wmhafiz/reactql-kea/pull/1

It seems to be working, except there's an error in the console log

> [KEA-LOGIC] Path starting with "scenes" is not connected to the reducer tree! (3) ["scenes","counter", "index"]

![Screenshot](https://image.ibb.co/dv542F/Screen_Shot_2017_08_04_at_11_01_55_AM.png)

Any idea where did i do wrong?
Thanks!

**Comment by mariusandra** [comment]
Hey! Great idea :)

The issue here is that the call to `keaReducer()` must happen before any calls to `kea()`. 

What happens now is that the call to [`import App`](https://github.com/wmhafiz/reactql-kea/blob/master/kit/entry/browser.js#L35) runs all the `@kea()` code and only [a few lines later](https://github.com/wmhafiz/reactql-kea/blob/master/kit/entry/browser.js#L43) the `keaReducer()` is called through `createNewStore(client)`.

While your code will still work and just give an annoying error if you define a `path = () => []` in your logic store, if you omit the `path`, everything will break, as the `keaReducer()` calls tell kea where to mount these "noname" reducers:

<img width="536" alt="screen shot 2017-08-04 at 09 54 27" src="https://user-images.githubusercontent.com/53387/28959497-f7cf2fa2-78fa-11e7-9429-2a7eaf61dd9a.png">

(I have updated the error message in `v0.20.5` to give a hint on how to fix the situation.)

The easiest way to fix this is to bring up the `keaReducer()` call by one level in `kit/lib/redux` like so:

```js
const scenesReducer = keaReducer('scenes')

export default function createNewStore(apolloClient) {
  const sagaMiddleware = createSagaMiddleware();

  const store = createStore(
    // By default, we'll use just the apollo reducer.  We can easily add our
    // own here, for global store management outside of Apollo
    combineReducers({
      apollo: apolloClient.reducer(),
      scenes: scenesReducer,
      ...unwind(),
    }),
    // ...
  );
}
```

This way it gets evaluated when the file is imported and everything will just work.

**Comment by mariusandra** [comment]
I also added some information about this to the [keaReducer API docs](https://kea.js.org/api/reducer)

**Comment by wmhafiz** [comment]
Yup that did it!  

There's a little problem with running the build script though after my commits so I've raised [an issue](https://github.com/reactql/kit/issues/54) to get support from the original author.

Thanks for the great support & documentation!

**Comment by wmhafiz** [comment]
So the author made the following remarks on the issue that I created:

> In ReactQL (as in classic Redux), actions are intended to be shared across multiple components and components simply listen to state or fire actions. Actions and reducers are defined once, not per-component like Kea seems to have. This might make dehydrating server state quite difficult.

What do you say about that claim?

**Comment by mariusandra** [comment]
Hey, I replied in the issue you referenced 2 posts ago.

**Comment by wmhafiz** [comment]
Nice! Thanks for taking the time to clarify the point & look into my issue. 😄 Really appreciate it

I'm also currently exploring [another redux/graphql boilerplate](https://github.com/sysgears/apollo-universal-starter-kit) which seems like more fitting to the use cases of my new project. The author seems to be more open to new feature PR as well, but I'll need sometime to understand the architecture.

I'm closing the issue for now.
