### ISSUE TITLE
kea combined with react-redux `connect` --> no kea sagas run

### ISSUE THREAD

**Issue by patrick-jones** [keajs/kea#31]
I found this while trying out kea in an existing app. I have a HOC that uses `connect` from react-redux. Long story short, you can't call `kea({...options})(MyComponent)` if `MyComponent` has already had `connect` (from react-redux) called on it.

If you do this and call the actions defined in your kea options, the actions will fire but the corresponding sagas will not run.

More (too much?) detail:

```js
export default function HOC(callback, mapStateToProps, mapDispatchToProps) {
  return function factory(WrappedComponent) {
    class Wrapper extends PureComponent {
      componentDidMount() {
        callback(this.props);
      }
      render() {
        return <WrappedComponent {...this.props} />
      }
    }

    return connect(mapStateToProps, mapDispatchToProps)(Wrapper);
  }
}

// in another file...
const Logic = kea({
    actions: () => ({
        greet: person => ({person}),
    }),
    workers: {
        handleGreeting: function* (action) {
            yield call(hello, action.payload.person);
            // etc...
        },
    },
    takeEvery: ({actions, workers}) => ({
      [actions.greet]: workers.handleGreeting,
    }),
});

const SillyComponent = props => (<div>Sent a greeting to {props.person}</div>);
// dispatch api call on mount...
const callback = (props) => props.actions.hello(props.person);

export default Logic(HOC(callback)(SillyComponent))
```

If you use `<SillyComponent person="Bob"/>` somewhere, it will dispatch the action when it mounts, but `workers.handleGreeting` will never run.

**Comment by mariusandra** [comment]
Hey, sorry for the radio silence. I've been in the hospital for the last 6 days - my daughter was born on Friday (everything is ok!), so I had no time to check this :).

I'll reply later today or in the worst case in the next days.

**Comment by mariusandra** [comment]
Hey, did the fix from #32 also solve this?

**Comment by mariusandra** [comment]
Hello, I checked and indeed the code you posted is not working. 

Here the trouble is with the order in which `componentDidMount` calls are executed. The saga's are started in this lifecycle method. (Not in `componentWillMount`, because [the docs say](https://facebook.github.io/react/docs/react-component.html#componentwillmount) "Avoid introducing any side-effects or subscriptions in this method." and because we don't want to start them for server rendering)

If you look at the components that are created in this example:

<img width="722" alt="screen shot 2017-08-25 at 14 43 28" src="https://user-images.githubusercontent.com/53387/29714498-cadae752-89a3-11e7-82c6-632680f61143.png">

`ConnectAdvanced` is the Redux HOC Kea creates, everything inside (`Connect`) is what Kea gets. The `componentDidMount` for `SillyComponent` will run first, followed by the `componentDidMount` for `Wrapper`, then for `Connect` and then for `ConnectAdvanced`.

Kea injects its saga-starting routine right before the `componentDidMount` of what it's given (in this case `Connect`)... or in case it gets a stateless functional component, it will inject it right before the `componentDidMount` of `ConnectAdvanced`. 

In you're example, you want the sagas to be started at `Wrapper`'s `componentDidMount` stage, but they are started after that. 

I think the best solution here is to run your callback in the `* start()` function in the logic instead of creating such a HOC for it. Also, it kind of feels like a code smell that you have a connect that's wrapping a connect. Admittedly, I don't know your situation, but you [can also use kea](https://kea.js.org/guide/migration) to pull in props from any random place in Redux.

Hope this helps :)

**Comment by patrick-jones** [comment]
I'm glad you had the chance to look at this. I had already worked around the problem and did not get a chance to debug it.

You are correct that it is not really elegant to have kea wrap another connected component. But since I am working kea into a project in which quite a lot of code is already written, the situation came up. In my case, the HOC was used to dispatch actions to fetch data during route changes. 

On one hand, it would be nice for kea to 'just work' with existing code. On the other hand, this particular situation is unusual enough that you probably should not complicate code by working around it.

I think it would be helpful if the docs specifically mentioned where saga startup/shutdown runs, specifically pointing out that sagas won't be available during `componentDidMount`, especially since `componentDidMount` is exactly where you would typically start dispatching actions to fetch data. Also, most people working with redux-sagas manually will wire them up during store creation and expect them to be always available.

**Comment by mariusandra** [comment]
Hey, the sagas are already running in the wrapped component's `componentDidMount`, just that in your case you wanted them before this lifecycle method: in your wrapped component's wrapped component's `componentDidMount` :).

The following code works fine:

```js
import React, { Component } from 'react'
import { kea } from 'kea'
import PropTypes from 'prop-types'

@kea({
  actions: () => ({
    showAlert: (id) => ({ id }),
    hideAlert: (id) => ({ id })
  }),
  reducers: ({ actions }) => ({
    visibleAlerts: [{}, PropTypes.object, {
      [actions.showAlert]: (state, payload) => ({ ...state, [payload.id]: true }),
      [actions.hideAlert]: (state, payload) => ({ ...state, [payload.id]: false })
    }]
  }),
  takeEvery: ({ actions }) => ({
    [actions.showAlert]: function * () {
      console.log('showAlert called')
    }
  })
})
export default class App extends Component {
  componentDidMount () {
    const { showAlert } = this.actions
    console.log('mounted')
    showAlert('Alert1')
  }

  render () {
    const { showAlert } = this.actions
    const { visibleAlerts } = this.props

    return (
      <div>
        {visibleAlerts.Alert1 ? 'alert1 visible' : ''}
        <button onClick={() => showAlert('Alert1')} disabled={visibleAlerts.Alert1}>Show Alert1</button>
        <br />
        {visibleAlerts.Alert2 ? 'alert2 visible' : ''}
        <button onClick={() => showAlert('Alert2')} disabled={visibleAlerts.Alert2}>Show Alert2</button>
      </div>
    )
  }
}
```

When I open the page, Alert1 is visible.

I have added a note to the docs a note about this (api -> start/stop/takeEvery/takeLatest).

Your case was indeed kind of special, and I'd prefer not to complicate the library too much. Let's see if this is a common issue people run into.

Glad to hear that you found a workaround for it :).
