### ISSUE TITLE
remote-redux-devtools

### ISSUE THREAD

**Issue by kevinfez** [keajs/kea#48]
Looks like this library changed recently to use a new ```getStore``` method that wraps of a lot of the redux stuff together. 

Is there a way to provide the compose function to ```getStore``` so that I can use the ```composeWithDevTools``` from [remote-redux-devtools](https://github.com/zalmoxisus/remote-redux-devtools#when-to-use-devtools-compose-helper)? 

Looks like there is a [fallback](https://kea.js.org/api/store) shown at the bottom of the ```getStore``` documentation, but using the new ```getStore``` abstraction would be nice.

"kea": "^0.25.1",

**Comment by mariusandra** [comment]
Hey, thanks for raising the issue! I'll find a way to solve this in `0.26`, released today or in the next days. In the end this will be as easy as doing `getStore({ compose: composeWithDevTools })`. However since this is a breaking change, it needs to be released in a new minor version... but I want to get some other stuff in there as well, hence the delay. :)

**Comment by mariusandra** [comment]
Hey, with `v0.26.2`, this is now possible. Just pass the function like I indicated in my previous comment. And let me know if it works or there's an issue :).

**Comment by mariusandra** [comment]
Hey @kevinfez , I haven't heard anything back, so I assume it's ok. Feel free to reopen if it's not.
