### ISSUE TITLE
Enable logic store to register at root level of Redux tree 

### ISSUE THREAD

**Issue by stefan-matmatch** [keajs/kea#58]
When setting the path option to:
`path: () => ['root']`

Then the following error occurs:
```
index.js:92 [KEA-LOGIC] Can not add reducer to "root". There is something in the way: {}
```

**Comment by mariusandra** [comment]
Hey, version `0.27.3` has this support. However make sure to activate the `keaReducer` on the path by passing it to the `getStore` helper:

```js
getStore({
  paths: [
    'kea',
    'scenes',
    'root'
  ]
})
```

Otherwise no `keaReducer` will be present to return the reducers. I might make this automatic in the future for people using `getStore` (and PRs are welcome), but for now it's like this.

**Comment by stefan-matmatch** [comment]
U r Awesome!
