### ISSUE TITLE
Actions created by kea-thunk are not available in reducer selectors

### ISSUE THREAD

**Issue by codinronan** [keajs/kea#69]
## Description

Let's say you have a Kea config that looks like the following, using kea-thunk:

```
{
  actions: () => ({
    updateName: (name) => ({ name }),
  }),
  reducers: ({ actions }) => ({
    name: ['Joe', PropTypes.string, {
      [actions.updateName]: (_, payload) => payload.name,
    }],
    isLoading: [false, PropTypes.bool, {
      [actions.updateName]: () => false,
      [actions.updateNameAsync]: () => true,
    }],
  }),
  selectors: ({ selectors }) => ({ }),
  thunks: ({ actions }) => ({
    updateNameAsync: async (name) => {
      await delay(1000);
      actions.updateName(name);
    },
  }),
}
```

In the `isLoading` reducer, the `[actions.updateName]` reducer DOES trigger; the `[actions.updateNameAsync]` reducer does not.

I looked into this, and it seems the reason for this is that the thunk (or any plugin) actions are not added to the collection. I suppose it could be a problem to know that what a plugin is defining *should* be actions.

I took a look and it looks like this can be modified here:
https://github.com/keajs/kea/blob/master/src/kea/actions/create.js#L37

Is that right? I might be able to take a crack at adding a PR for this.

Thanks :) I really like Kea.

Edit: By the way this isn't a *huge* issue, the obvious solution is to simply have your thunks call one of the standard actions directly, and in fact you'd usually expect to do exactly that. Adding this just avoids having to add standard actions like `setLoading: (isLoading) => ({ isLoading })`

**Comment by mariusandra** [comment]
Hey!

The issue is that thunks are not **really** actions :). When a "standard" action is called, we dispatch a Redux action with the appropriate `{ type, payload, etc }` to the store. When a thunk is called, just the thunk function is executed and no action is automatically dispatched into Redux.

The reducers in Kea, like any other reducers in Redux, get re-evaluated only when a new action is dispatched to the store.

It's the same with `redux-thunk` that `kea-thunk` uses internally: actions are only dispatched when you explicitly `dispatch` them from within thunk functions. Not when you run the thunk functions themselves.

It could be possible to automatically dispatch a new action when a thunk function is called, but I'd rather not since I'd like to keep functional parity with redux-thunk and avoid magical surprises :).

Thus, yeah, you'll need to call the `setLoading` action manually for your example :).

Thanks for reporting and the nice comments though... and happy holidays! :)
