### ISSUE TITLE
what would be the best way to trigger thunks/sagas triggered from a connected action?

### ISSUE THREAD

**Issue by ingoclaro** [keajs/kea#81]
I have a logic of a component, I would like to create a separate logic that triggers thunks (not a reducer!) when that logic fires an action. Currently it's possible to use connected actions for the reducers, but you can't trigger other actions within a reducer, which is ok since we don't want side effects in a reducer. How could I 'listen' to some logic's actions and trigger thunks or other type of side effects?

example:
```
const firstLogic = kea({
    actions: ({ actions, constants }) => ({
      updateName: name => ({ name }),
    }),
    reducers: ({ actions, constants }) => ({
      name: ['chirpy', PropTypes.string, {
        [actions.updateName]: (state, payload) => {
          return payload.name
        }
      }],
    })
  })

const secondLogic = kea({
  connect: {
    actions: [firstLogic, ['updateName']],
  },
  thunks: ({ actions, dispatch, getState }) => ({
      someAsyncStuff: async name => {
        // go wild.
      },
    }),
  reducers: ({actions}) => ({
    nameChanged: [false, PropTypes.boolean, { //this works as expected.
      [actions.updateName]: () => true
    },
    dont: [false, PropTypes.boolean, {
      [actions.updateName]: (state, payload) => { //don't do this, but how can I get the intended result?
        actions.someAsyncStuff(payload.name)
      }
    },
  })
})
```

**Comment by ingoclaro** [comment]
I think I may be approaching this the wrong way, I'm trying an alternative

**Comment by ingoclaro** [comment]
ok, so initially I had a component with a dynamic logic (using `key` attribute), because I'm using it in 2 different places.
Since the thunk plugin doesn't work with dynamic logic I couldn't trigger the action from the component using a thunk there.

I ended up transforming that component to a stateless one, passing everything as props and duplicating the logic in the components that use it. It's less than ideal but it works, so I don't have an immediate need for something like this issue, but I'm still interested in your thoughts on how to solve this, I guess that probably having the thunk in the dynamic component would solve this.

**Comment by mariusandra** [comment]
Hey,
The easiest way to listen to actions is to use sagas. They have just the tools for the job: `takeEvery` and `takeLatest`.

It could be possible to write a non-saga kea-plugin that will `subscribe` to the redux store, listen to actions and run specific *thunky* functions when those actions are dispatched... but that will soon run into issues (e.g. promise cancellation) and slowly develop itself into a clone of `redux-saga`. I'd much rather have people use sagas than support such an alternative implementation.

That said, such a `kea-subscribe` plugin shouldn't be that hard to do.

The only issue is to know when to stop and start listening to actions. It's more complicated than you might initially think with dynamic components that rely on React's lifecycle, `@connect`ed logic, orphaned logic stores, etc. I've managed to solve it some for `kea-saga`, but this logic should be abstracted into `kea` itself so that other plugins (e.g. `kea-thunk`) could use it. But this will still take time...

The feature of thunks working with dynamic logic stores is waiting behind this abstraction as well.

**Comment by ingoclaro** [comment]
cool, I'll take a look into kea-saga
